name: Update Docker on Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull latest code
        run: |
          cd /home/ironi/Documents/hirator
          git pull origin main

      - name: Rebuild and restart Docker container
        run: |
          cd /home/ironi/Documents/hirator
          docker compose up -d --build
